version: "3.4"

services:

  mongodb:
    image: "mongo:6.0.2"

  grapqhl_api:
    build: .
    ports:
      - "80:80"
    environment:
      - env_mongodb_url=mongodb://mongodb
      - env_mongodb_dbname=country_db
    entrypoint: sh /code/start_server.sh
